apiVersion: v1
kind: Service
metadata:
  name: {{name}}
spec:
  selector: { app: {{name}} }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
