name: Deploy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kubectl apply
        run: |
          kubectl apply -f helm/templates/
        env:
          KUBECONFIG: 
